
# Set 'true' to ignore this script
ignored: true

trigger: "stage"  # required
trigger_type: "MATCH"  # required
trigger_value: 1  # optional

texts: 
  ja:
    - "読み上げられるテキストです"
    - "複数行をセットすると"
    - "順番に読み上げます"
  en:
    - "This is a text to read aloud"
    - "If you set multiple lines"
    - "It reads in order"
