# これはサンプルなのでignore: trueしています

# trueでこのyamlファイルを無効化する
ignore: true

# テキスト読み上げのトリガー
# command, stage に対応
trigger: "command"

# トリガーとなるレフェリーコマンド
command: -1

# トリガーとなるレフェリーコマンド
stage: -1

# 読み上げるテキスト
# 複数指定した場合は連続で読み上げる
texts: 
  - "読み上げられるテキストです"
  - "複数行をセットすると"
  - "順番に読み上げます"
